---
background-color: whitesmoke
title: ""
subtitle: ""
author: ["Johannes Piller",
"Department of Statistics, LMU Munich"]
output:
  xaringan::moon_reader:
    lib_dir: libs
    seal: false
    nature:
      ratio: '16:9'
      highlightStyle: zenburn
      highlightLines: true
      countIncrementalSlides: false
      slideNumberFormat: "%current%/%total%"
    css: ["default", "default-fonts", "metropolis-fonts", "ninjutsu", "custom.css"]
---
class: title-slide, middle

<br><br><br><br>

<h2 style="color:#1F1414">
Flexible Additive Models for Survival and Event-history Analysis
</h2>
<h3 style="color:#1F1414"> useR! Salzburg - Webinar </h3>

.font120[
Johannes Piller, Andreas Bender<br>
Department of Statistics, LMU Munich <br>
Munich Center for Machine Learning (MCML)
]

<br>
Compiled: `r Sys.Date()`


```{r input-setup, child = "setup.Rmd", eval = TRUE}
```

```{r input-speakers, child = "speakers.Rmd", eval = TRUE}
```

```{r input-schedule, child = "schedule.Rmd", eval = TRUE}
```

```{r input-overview, child="examples-overview.Rmd", eval = TRUE}
```

```{r input-basics, child="basics.Rmd", eval = TRUE}
```

```{r input-tldr, child = "pamms-tldr.Rmd", eval = TRUE}
```

```{r input-pem, child = "pem.Rmd", eval = TRUE}
```

```{r input-lin, child = "linear-effects.Rmd", eval = TRUE}
```

<!--simple ex: aus der vignette: MGUS data -->

```{r tve, child = "time-varying-effects.Rmd", eval = TRUE}
```

<!-- time-dep, stratification ex:  tumor data -->

<!-- lunch -->

```{r left-truncation, child = "left-truncation.Rmd", eval = TRUE}
```

```{r input-cr, child = "competing-risks.Rmd", eval = TRUE}
```

```{r input-ms, child = "multi-state.Rmd", eval = TRUE}
```

```{r input-outlook, child = "outlook.Rmd", eval = TRUE}
```

<!-- ex -->

<!-- Bibliography -->
```{r input-references, child = "references.Rmd", eval = TRUE}
```

<!-- Backup -->

```{r input-backup, child="backup.Rmd", eval = TRUE}
```


