
---
class: inverse, middle, center

.center[
.font150[
**4. Summary and Outlook**
]
]

<html>
  <div style='float:left'></div>
  <hr color='#005500' size=2px width=900px>
</html>


---
# **`pammtools`**: Hazard, Density and Survival ... important utility functions are implemented

*Pre-Processing*:

- `as_ped(data, formula, cut, ...)` creates PED-formatted data suitable for PAMMs.
Also merges additional datasets for time-dependent covariates according to the specification in `formula` and handles left-truncation.

*Post-Processing*:

- `make_newdata(x, <optional covariate specifications>)` flexibly creates PED-formatted data suitable to calculate any quantity of interest (hazrd, survival, hazard ratios, etc.), using `add_<quantity>`-functions (unspecified covariates are set to their sample means or modes by default).
- `add_<quantity>(newdata, object)` computes PAMM point estimates (and CIs) from a model `object` on `newdata` and appends them to `newdata`.  Resulting `data.frame` useful for custom visualizations etc.
   Flavors: `add_surv_prob`, `add_hazard`, `add_cumu_hazard`, `add_cif`, `add_term`, `add_trans_prob`
- `tidy_fixed()`, `tidy_re()`, `tidy_smooth()` extract estimated coefficients / smooth effects and CIs as clean `data.frames` for visualization
- `gg_fixed()`, `gg_smooth()`, `gg_slice()`, ... etc for direct `ggplot2` viz of estimates



---
# Beyond (mgcv) GAMMs

Here we focused on **`mgcv`** GAMMs as backend for computation (which makes sense!), however, in some situation another backend might be advantageous, e.g.

- **`gamm4`**: For GAMMs with more flexible random effects
- **`scam`**: GAMMs with monotonicity constraints
- **`brms`**: Fully Bayesian estimation of (hierarchical) GAMMs
- **`mboost`**: Boosting GAMMs for automated variable/term selection
- ...

Most of the functionality of **`pammtools`**, especially data trafo can be used as before

Some adjustments w.r.t. to post-processing might be necessary

Contributions are welcome!
